# Generated by Django 4.2.7 on 2023-11-23 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_Achievements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='scores',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
